"""Facebook Page poster tool.

Publishes a post to a Facebook Page using the Graph API, attaching a link
to a blog article. The link's preview card (image + title + description)
is auto-generated by Facebook from the article's Open Graph meta tags,
which Blogger sets by default.
"""
import os
import logging
import json

import requests

logger = logging.getLogger(__name__)


def post_to_facebook(message: str, link_url: str) -> dict:
    """Publish a post to the configured Facebook Page.

    Args:
        message: The text of the post. Keep under ~200 characters for
            best engagement — Facebook truncates longer text in feeds.
            Should be a conversational hook, not a formal title.
        link_url: The URL the post links to. Facebook auto-renders a
            preview card from the link's Open Graph tags.

    Returns:
        On success: {"facebook_post_url": "<https URL of the post>",
                     "facebook_post_id": "<page_id>_<post_id>"}
        On failure: {"error": "<reason>"}
    """
    page_id = os.environ.get("FACEBOOK_PAGE_ID")
    page_token = os.environ.get("FACEBOOK_PAGE_ACCESS_TOKEN")
    api_version = os.environ.get("FACEBOOK_API_VERSION", "v21.0")

    if not page_id or not page_token:
        return {"error": "Missing FACEBOOK_PAGE_ID or FACEBOOK_PAGE_ACCESS_TOKEN env var"}

    if not link_url or link_url.startswith("ERROR:"):
        return {"error": "Cannot post to Facebook without a valid link URL"}

    endpoint = f"https://graph.facebook.com/{api_version}/{page_id}/feed"
    payload = {
        "message": message,
        "link": link_url,
        "access_token": page_token,
    }

    try:
        # 30s timeout — Facebook usually responds in <2s, but the link
        # preview generation step can occasionally take longer.
        response = requests.post(endpoint, data=payload, timeout=30)
    except requests.exceptions.RequestException as e:
        logger.exception("Facebook API network error")
        return {"error": f"Facebook API network error: {e}"}

    # Parse the JSON regardless of status — Facebook returns useful
    # error details in the response body even on 4xx/5xx.
    try:
        body = response.json()
    except json.JSONDecodeError:
        return {"error": f"Facebook API returned non-JSON: HTTP {response.status_code}"}

    if not response.ok:
        # Graph API errors look like:
        # {"error": {"message": "...", "type": "...", "code": ..., ...}}
        fb_error = body.get("error", {})
        msg = fb_error.get("message", "unknown error")
        code = fb_error.get("code", "unknown")
        return {"error": f"Facebook API error (code {code}): {msg}"}

    # Success response: {"id": "PAGEID_POSTID"}
    post_id = body.get("id")
    if not post_id:
        return {"error": f"Facebook returned no post id; body: {body}"}

    # Construct the post URL. Graph API doesn't return one directly.
    # Format is https://www.facebook.com/<page_id>/posts/<post_id_suffix>
    # The id field is "<page_id>_<post_id_suffix>".
    if "_" in post_id:
        post_suffix = post_id.split("_", 1)[1]
        post_url = f"https://www.facebook.com/{page_id}/posts/{post_suffix}"
    else:
        post_url = f"https://www.facebook.com/{post_id}"

    return {
        "facebook_post_url": post_url,
        "facebook_post_id": post_id,
    }